name: CI/CD

on: 
  push:
    branches: 
      - '*'
      - '!master'
      - '!beta'

jobs:
  build:
    name: Build WebWindow
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        include:
        - os: windows-latest
          RUNTIME: win-x64
          FOLDER: FluxHelmTool.Windows

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true

    - name: Publish
      working-directory: ${{matrix.FOLDER}}
      run: dotnet publish -r ${{matrix.RUNTIME}} -c Release -p:SelfContained=true -p:PublishSingleFile=true -p:PublishTrimmed=true -p:DebugType=None -p:IncludeNativeLibrariesForSelfExtract=true -o /bin/Release/publish

    - uses: actions/upload-artifact@v2
      with:
        name: FluxHelmTool-${{matrix.RUNTIME}}
        path: ${{matrix.FOLDER}}/bin/Release/publish
