name: CI/CD

on: 
  push:
    branches: 
      - '*'
      - '!master'

jobs:
  build:
    name: Build WebWindow
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
        - os: windows-latest
          RUNTIME: win-x64
          FOLDER: FluxHelmTool.Windows
        - os: macos-latest
          RUNTIME: osx-x64
          FOLDER: FluxHelmTool.macOS
    steps:
    - uses: actions/checkout@v1

    - name: setup-xamarin
      if: matrix.os == 'macos-latest'
      uses: maxim-lobanov/setup-xamarin@v1
      with:
        xamarin-mac-version: latest # specify 'latest' keyword to pick up the latest available version
        xcode-version: latest # set the latest available Xcode 11

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Publish
      working-directory: ${{matrix.FOLDER}}
      run: dotnet publish -r ${{matrix.RUNTIME}} -c Release -p:SelfContained=true -p:PublishSingleFile=false -p:PublishTrimmed=false -p:DebugType=None

    - uses: actions/upload-artifact@v1
      with:
        name: FluxHelmTool-${{matrix.RUNTIME}}
        path: ${{matrix.FOLDER}}/bin/Release/netcoreapp3.1/${{matrix.RUNTIME}}/publish
