name: Release

on:
  push:
    branches:
      - master
      - beta

jobs:
  bump_version:
    name: Bump Version
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      id: semantic
      with:
        semantic_version: 17.3
        dry_run: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set Version
      run: |
        $new_tag = "${{ steps.semantic.outputs.new_release_version }}";
        Write-Output $new_tag;
        Set-Content -Path "new_tag.config" -Value $new_tag;
      shell: pwsh

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: new_tag.config
        path: new_tag.config

  build_webwindow:
    name: Build WebWindow
    needs: [bump_version]    
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        include:
        - os: windows-latest
          RUNTIME: win-x64
          FOLDER: FluxHelmTool.Windows
    steps:
    - uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v1.0.0
      with:
        name: new_tag.config
        path: .

    - name: Set Version
      id: version
      run: |
        $new_tag = (Get-Content -Path "new_tag.config").Trim();
        Remove-Item -Path "new_tag.config";
        Write-Output $new_tag;
        echo "::set-output name=tag::$($new_tag)"
        echo "::set-output name=value::$($new_tag.TrimStart('v'))"
      shell: pwsh

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Publish
      working-directory: ${{matrix.FOLDER}}
      run: dotnet publish -r ${{matrix.RUNTIME}} -c Release -p:SelfContained=true -p:PublishSingleFile=true -p:PublishTrimmed=true -p:DebugType=None -p:Version=${{ steps.version.outputs.value }}
      shell: pwsh

    - uses: actions/upload-artifact@v1
      with:
        name: FluxHelmTool-${{matrix.RUNTIME}}
        path: ${{matrix.FOLDER}}/bin/Release/netcoreapp3.1/${{matrix.RUNTIME}}/publish

  release:
    name: Upload Release Asset
    needs: [bump_version, build_webwindow]
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact win-x64
      uses: actions/download-artifact@v1
      with:
        name: FluxHelmTool-win-x64
        path: dist/FluxHelmTool-win-x64

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      id: semantic
      with:
        semantic_version: 17.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}